UTDNebula/jupiter

pages/index.tsx
- Updated homepage tagline to “Get Connected on Campus”.
-  Increased font size and added letter spacing to look slightly better.
- Closes #47
=> fix: Update homepage tagline

components/navigation/Navbar.tsx
Should remain around the same size when making screens smaller
=> Update navbar logo

components/EventCard.tsx, pages/index.tsx
Created EventCard component and added it to the homepage as a placeholder for the events section
Resolves https://github.com/UTDNebula/jupiter/issues/9
=> Events placeholder

components/DirectoryOrgs.tsx, components/OrgHeader.tsx, pages/directory/[orgName].tsx, pages/directory/index.tsx
Followed the Student Org Directory Frame from the Figma
=> 72 org directory page

src/components/ContactButtons.tsx, src/components/OrgHeader.tsx, src/models/club.ts, src/models/contacts.ts
Note: This is my first pull request, so feel free to be as honest as possible, so I can learn  whether that is in my naming, coding logic, etc
Feature: 
- Creates the correct number of buttons to each UTD organization social media platform. I.E. let say UTD Nebula has 4 social media platform, so when the user clicks on the "learn more" four buttons should appear that link to each social media platform UTD nebula uses. 
My approach: 
1) Change the Contact object to accept the different types of platform as well as the url to the social media platform 
2) Create a dummy data set to test out the contact button 
3) Create a tsx file that will load the Contact Buttons
- This file will map to each element in the Contact array and connect the correct Icon and link to that button
=> dynamic-buttons-contact

README.md
fixes instructions for setting up a database, matching them with the new migration scripts.
=> update instructions for setting up a database

src/components/Header.tsx, src/components/SearchBar.tsx, src/pages/directory/[clubId].tsx, src/pages/events.tsx
In #140 I made changes to how the search bar worked, I've decided this should  be a different pr since It's a more technical change to how search bars are implemented, rather than a styling change, and should be considered independent of the style changes
- header changes
- I made a BaseHeader, that sets the spacing and layout for the headers but lets the contents be different. then the default header and event header can pass in what they should have inside, In this case the different search bars.
- This change should keep header padding uniform across the project, but might end up not the best idea if we don't want headers coupled like this.
- search bar component
- There is a new search bar component that handles how all search bars should look and behave. But a parent component would …
=> Search bar changes

next.config.mjs, package-lock.json, package.json, src/components/Header.tsx, src/pages/auth.tsx
#109 
I have replaced the placeholder profile icon we have with the user's profile pic from the session. I have also added the sign in and sign out links when the user isn't logged in and a log out link under the dropdown menu.
=> Replaced the place holder profile circle with actual profile image and added a dropdown menu

src/server/db/migrations/0002_fuzzy_shen.sql, src/server/db/migrations/meta/0002_snapshot.json, src/server/db/migrations/meta/_journal.json, src/server/db/schema.ts
I changed id column type to text from integer
=> Fixed incorrect schema type issue in the database table events

src/components/Sidebar.tsx, src/pages/feedback.tsx, src/pages/history.tsx, src/pages/liked.tsx, src/pages/settings.tsx
I implemented temporary placeholder pages for features not yet implemented: History, Liked, Feedback, and Settings. Before it would give a 404 error, but now it tells users that these pages are still being worked on.
=> (Jup 153) Placeholder Pages created for Features not Implemented

src/components/settings/SettingsDropdown.tsx, src/components/settings/SettingsInput.tsx, src/pages/settings.tsx, src/server/db/models.ts
Replaces input fields that are enums to drop downs
=> Drop downs for enums in settings page

src/components/SidebarItems.tsx
Added a hover state so that when you mouse over one of the sidebar items it looks the same as the active item. Also this is my first pull request here so lmk if I'm doing anything wrong.
=> Added hover state to sidebar

src/pages/event/[eventId].tsx, src/server/api/routers/event.ts
- Added individual pages for events under /event/[eventId]
- Added byId procedure to events API router
- Event pages link to host club through titles
=> JUP-24 - Event Description Page

src/components/EventCalendarCard.tsx
quick fix to display 12 hour format with AM and PM for event display - For JUP-31
=> display12hourformat

src/components/OrgHeader.tsx
changed the tags on club pages into links so that users can find similiar clubs.
=> turn tags on clubs into links.

src/components/Carousel.tsx, src/components/OrgHeader.tsx
- Carousel cards can be clicked and it will take you to the featured club
- navigation buttons are now static, as opposed to being associated with each card. this should be better i think. or at least makes more sense organizationally.
=> Improve front page carousel

src/components/Sidebar.tsx
Main categories on sidebar to Main
=> Main categories on sidebar to Main

src/app/page.tsx, src/components/DirectoryOrgs.tsx, src/components/InfiniteScrollGrid.tsx, src/components/JoinButton.tsx, src/components/OrgDirectoryGrid.tsx, src/components/ScrollTop.tsx, src/components/TagFilter.tsx, src/server/api/routers/club.ts
Initial work for infinite query. Might make it update on scroll if we think that looks better
=> Update org grid for infinite query :)

src/app/event/[id]/page.tsx, src/components/RegisterButton.tsx
-RegisterButton component for toggling registration in an event; shows registration status
-Event page gets registration status on load and passes it to RegisterButton
=> Jup 45 - View Register Status

src/components/admin/OrgTable.tsx, src/server/api/routers/admin.ts, src/server/db/migrations/0006_narrow_mad_thinker.sql, src/server/db/migrations/meta/0006_snapshot.json, src/server/db/migrations/meta/_journal.json, src/server/db/schema/club.ts
added a column to the club table indicating whether or not the listing came from the SOC or not. Should be useful as we get more actual organizations on the platform.
=> add flag to clubs for soc data

src/app/layout.tsx, tailwind.config.cjs
this adds the Inter font to the tailwind config so that it is applied across the project.
=> fix: Inter font not rendering

src/app/directory/create/page.tsx, src/app/manage/[clubId]/(dashboard)/layout.tsx, src/app/manage/[clubId]/edit/officers/page.tsx, src/app/manage/page.tsx, src/app/settings/page.tsx, src/utils/redirect.ts
protected routes will now redirect with a callback so that the user is redirected back to the page they came from improving user experience.
=> fix: callbacks for nextAuth signin

CODEOWNERS
=> codeowners -> main

.github/workflows/generateCheck.sh, .github/workflows/prettierCheck.yml, .prettierrc.js, .prettierrc.mjs, src/app/manage/[clubId]/create/CreateEventForm.tsx, src/app/manage/[clubId]/create/EventCardPreview.tsx, src/app/manage/[clubId]/create/TimeSelect.tsx, src/app/manage/[clubId]/create/page.tsx, src/server/api/routers/event.ts, src/utils/formSchemas.ts
adjust formatting rules and fix the formatting checker.
=> Prettier changes

.github/workflows/prettierCheck.yml
when I changed the way the prettier output is done, i messed up the status being passed to the next step, **should** be fixed now
=> fix status output

src/server/api/routers/club.ts
listedOfficers wasn't accessible if you weren't logged in.
=> private -> public

src/components/club/listing/ClubInfoSegment.tsx
This was causing an error that prevented club directory pages from loading.
=> remove president info from left side of club info

package-lock.json
big next.js vulnerability, needs version bump
=> update package-lock.json for next update

.prettierrc.mjs, src/app/layout.tsx
Only initialize google analytics on prod. Just made this change to the other Nebula sites.
Also, changed prettier to not care about line endings. Git can handle that.
=> Google analytics only on prod

drizzle.config.ts, package-lock.json, package.json, src/app/events/page.tsx, src/env.mjs, src/server/db/index.ts, src/server/db/migrations/0001_next_marrow.sql, src/server/db/migrations/meta/0000_snapshot.json, src/server/db/migrations/meta/0001_snapshot.json, src/server/db/migrations/meta/0002_snapshot.json, src/server/db/migrations/meta/0003_snapshot.json, src/server/db/migrations/meta/0004_snapshot.json, src/server/db/migrations/meta/0005_snapshot.json, src/server/db/migrations/meta/0006_snapshot.json, src/server/db/migrations/meta/0007_snapshot.json, src/server/db/migrations/meta/0008_snapshot.json, src/server/db/migrations/meta/0009_snapshot.json, src/utils/eventFilter.ts
upgrades both drizzle and zod to newer versions, bringing performance improvements for both runtime and dev and some new features for drizzle.
=> Drizzle Upgrade

next.config.mjs, src/app/event/[id]/page.tsx, src/app/page.tsx, src/components/admin/CarouselCards.tsx, src/components/club/ClubCard.tsx, src/components/club/directory/Carousel.tsx, src/components/club/listing/ClubInfoSegment.tsx, src/components/settings/ClubPill.tsx, src/components/settings/ClubSelector.tsx, src/components/settings/FormCard.tsx, src/server/api/routers/storage.ts, src/server/db/schema/club.ts, src/utils/storage.ts
- Change post to use blobs instead of string
- Move storageAPI helper outside of trpc so that it can be used in other contexts (RSCs)
- remove outdated `image` column on club table
- support loading remote images from the google cloud storage bucket
=> Image storage fixes

src/server/api/routers/club.ts, src/server/db/schema/club.ts
=> fix: tag column has the wrong name

src/app/manage/[clubId]/edit/officers/EditOfficerForm.tsx, src/components/nav/NavMenu.tsx, src/components/nav/SidebarItems.tsx
This change aims to resolve #312  by adding key for fieldId in a similar structure to EditListedOfficerForm. Additionally, I set 'title' to be non-empty when appending a user, and set the 'deleted' array to reset on 'Discard Changes' press.
I was able to get the form submit on my environment, but I am open to any revision/changes for further resolution.
=> EditOfficer Form Submit Bug Fixes
